version: '3.8'

services:
  pg:
    image: postgres:16.2
    env_file:
      - .env
    command: -c 'max_connections=200'
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U$$POSTGRES_USER --dbname=$$POSTGRES_DB" ]
      start_period: 30s
      interval: 1s
      timeout: 5s
      retries: 10

  pg_migration:
    depends_on:
      pg:
        condition: service_healthy
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./:/project
    command: -verbose -path=/project/migrations -database 'postgres://'$POSTGRES_USER':'$POSTGRES_PASSWORD'@pg:5432/'$POSTGRES_DB'?sslmode=disable' up

  bob_gen:
    depends_on:
      pg_migration:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/project
    command: -c /project/bobgen_config/bobgen.yaml
