// Code generated by BobGen psql v0.26.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"net"

	"github.com/stephenafamo/bob/types"
)

// Make sure the type types.Stringer[net.HardwareAddr] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.Stringer[net.HardwareAddr])(nil)

// Make sure the type types.Stringer[net.HardwareAddr] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.Stringer[net.HardwareAddr])
