// Code generated by BobGen psql v0.26.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"net"
	"slices"
	"testing"

	"github.com/stephenafamo/bob/types"
)

func TestRandom_int64(t *testing.T) {
	t.Parallel()

	seen := make([]int64, 10)
	for i := 0; i < 10; i++ {
		seen[i] = random[int64](nil)
		for j := 0; j < i; j++ {
			if seen[i] == seen[j] {
				t.Fatalf("random[int64]() returned the same value twice: %v", seen[i])
			}
		}
	}
}

func TestRandom_types_Stringer_net_HardwareAddr_(t *testing.T) {
	t.Parallel()

	seen := make([]types.Stringer[net.HardwareAddr], 10)
	for i := 0; i < 10; i++ {
		seen[i] = random[types.Stringer[net.HardwareAddr]](nil)
		for j := 0; j < i; j++ {
			if slices.Equal(seen[i].Val, seen[j].Val) {
				t.Fatalf("random[types.Stringer[net.HardwareAddr]]() returned the same value twice: %v", seen[i])
			}
		}
	}
}
